name: Push Alpine Package to Cloudsmith

on:
  push:
    branches:
      - main

jobs:
  upload-package:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Cloudsmith CLI
      run: |
        pip install cloudsmith-cli

    - name: Upload Alpine package to Cloudsmith
      env:
        CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
      run: |
        cloudsmith push alpine ${{ secrets.CLOUDSMITH_ORG }}/${{ secrets.CLOUDSMITH_REPO }} test/feature/*.apk --api-key $CLOUDSMITH_API_KEY
