name: Push Hex

on:
  push:
    branches:
      - master
  schedule:
    # run every 6 hours
    - cron: '0 0,6,12,18 * * *'

jobs:
  push:
    runs-on: ubuntu-latest
    name: Hex Push Demo
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Push
        id: push
        uses: ./
        with:
          api-key: ${{ secrets.CLOUDSMITH_API_KEY }}
          command: "push"
          format: "hex"
          owner: "cloudsmith"
          repo: "actions"
          republish: "true" # needed ONLY if version is not changing
          file: "test/fixture/cloudsmith-hex-example-1.0.0.tar" #real file that will repeat versions
