name: Push Alpine Package to Cloudsmith

on:
  push:
    branches:
      - main

jobs:
  upload-package:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Cloudsmith CLI
      run: |
        pip install cloudsmith-cli

    - name: Upload Alpine package to Cloudsmith
      env:
        CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
        CLOUDSMITH_ORG: ${{ secrets.CLOUDSMITH_ORG }}
        CLOUDSMITH_REPO: ${{ secrets.CLOUDSMITH_REPO }}
        CLOUDSMITH_DISTRO: "alpine"  # Assuming the distribution is Alpine
        CLOUDSMITH_RELEASE: "v3.18"  # Replace with the actual release version if known
      run: |
        cloudsmith push alpine $CLOUDSMITH_ORG/$CLOUDSMITH_REPO/$CLOUDSMITH_DISTRO/$CLOUDSMITH_RELEASE test/fixture/*.apk --api-key $CLOUDSMITH_API_KEY
