name: Push Alpine

on:
  push:
    branches:
      - master
  schedule:
    # run every 6 hours
    - cron: '0 0,6,12,18 * * *'

jobs:
  push:
    runs-on: ubuntu-latest
    name: Alpine Push Demo
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Push
        id: push
        uses: ./
        with:
          api-key: ${{ secrets.CLOUDSMITH_API_KEY }}
          command: "push"
          format: "alpine"
          owner: "cloudsmith"
          repo: "actions"
          distro: "alpine"
          release: "v3.9"
          republish: "true" # needed ONLY if version is not changing
          file: "test/fixture/cloudsmith-alpine-example-1.0.0-r0.apk" #real file that will repeat versions
